# Generated by Django 2.2.4 on 2019-08-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190808_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este e-mail já está cadastrada em nosso sistema.'}, max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='telefone_escola',
            field=models.CharField(error_messages={'unique': 'Este número de telefone já existe em nosso sistema. Verifique e tente novamente.'}, max_length=12, unique=True, verbose_name='Número de Telefone'),
        ),
    ]
