# Generated by Django 2.2.4 on 2019-08-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190808_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='confirmar_senha',
            field=models.CharField(default='senha', max_length=12, verbose_name='Confirme a senha de acesso'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este e-mail já está cadastrado em nosso sistema.'}, max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='nome_escola',
            field=models.CharField(error_messages={'unique': 'Escola com este nome já está cadastrado em nosso sistema.'}, max_length=255, unique=True, verbose_name='Nome da Escola'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='senha_acesso',
            field=models.CharField(default='senha', max_length=12, verbose_name='Registre uma senha de acesso'),
        ),
    ]
